name: ghpages 

on:
  push:
    branches:
      - pages-reorg

defaults:
  run:
    working-directory: Exercise_4
# See https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
