site_name: FHIR for Researchers

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Exercise 4:
    - exercise-4/index.md
    - exercise-4/part-1.md
    - exercise-4/part-2.md
    - exercise-4/part-3.md
    - exercise-4/conclusion.md
    - exercise-4/glossary.md

extra_css:
  - stylesheets/extra.css

copyright: "Copyright &copy; 2022 The MITRE Corporation. PRS Release Number: 21-3456"
